apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: umat-api
  description: App Modernization API details
spec:
  type: openapi
  lifecycle: experimental
  owner: brillio-engineering
  system: app-modernization
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: App Modernization API
      license:
        name: MIT
    servers:
      - url: http://localhost:8080
    paths:
      /handleSolutionRecommWithQuestionnaire:
        post:
          summary: Provides Recommended Cloud Strategy
          description: Suggestes cloud strategy based on questionnaire responses.
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    questionnaire:
                      type: object
                      properties:
                        What is the level of expertise in your development and operations teams regarding cloud-native technologies?:
                          type: string
                          example: "High Expertise"
                        Is there a need for rapid migration with minimal disruption to existing business operations?:
                          type: string
                          example: "Yes"
                        What is the current financial priority for this migration project?:
                          type: string
                          example: "Lower Cost and Value Emphasis"
                        What is the data sensitivity and compliance requirements for your applications?:
                          type: string
                          example: "High Sensitivity"
                        What is the anticipated scale of your application in the next 2-3 years?:
                          type: string
                          example: "Rapid Growth"
                        How closely tied are your applications to specific on-premises infrastructure or technologies?:
                          type: string
                          example: "Strongly Tied"
          responses:
            '200':
              description: Solution processed successfully.
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      explanation:
                        type: string
                        description: The explanation of the recommended strategy.
                      abc:
                        type: array
                        items:
                          type: object
                          properties:
                            label:
                              type: string
                            value:
                              type: number
                  example: # Sample response
                    explanation: "Replatform is recommended..."
                    abc:
                      - label: "Rehost"
                        value: 0.6
                      - label: "Refactor"
                        value: 0.7
                      - label: "Replatform"
                        value: 0.9
            '400':
              description: Bad Request. Invalid input data.
            '500':
              description: Internal Server Error.
